spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restdb?useSSL=false&serverTimezone=UTC
    username: root
    password: hyxx0906
mybatis:
  type-aliases-package: com.yxh.demorest.entity
  mapper-locations: classpath:mapper/*.xml